language: go
go:
    - 1.15
env:
    - IMAGE_NAME=asia.gcr.io/gcp-akash-287109/golang-like-service
before_install:
    - pwd
    - ls
    -  openssl aes-256-cbc -K $encrypted_0a08b4698b52_key -iv $encrypted_0a08b4698b52_iv -in gcp-akash-287109-41bac7d58115.json.enc -out ~/gcp-akash-287109-41bac7d58115.json -d
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce
script:
    - go test -v
    - go build
after_success:
    - cat ~/gcp-akash-287109-41bac7d58115.json | docker login -u _json_key --password-stdin https://asia.gcr.io
    - docker build . --tag "$IMAGE_NAME"
    - git_sha="$(git rev-parse --short HEAD)"
    - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:develop"
    - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}-develop"
    - docker push "${IMAGE_NAME}:develop" && docker push "${IMAGE_NAME}:${git_sha}-develop"
